---
plugins:
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - 'misc/**/*'
    - 'dist/**/*'
    - 'vendor/gems/**/*'
    - 'plugins/**/*'
  Include:
    - 'plugins/*openbsd_package/**/*'

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
  Max: 20

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 40

Metrics/PerceivedComplexity:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: single_quotes

Naming/FileName:
  Exclude:
    - Gemfile
    - Rakefile
