---
plugins:
  - rubocop-rake
  - rubocop-itamae
  - rubocop-thread_safety
  - rubocop-performance


AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Include:
  - Rakefile
  - Gemfile
  - "*.gemspec"
  - "cookbooks/**/*"
  - "plugins/**/*"
  - "lib/**/*"
  - "bin/hocho"
  Exclude:
  - "bin/**/*"
  - "cookbooks/*/files/**/*"
  - "cookbooks/*/templates/**/*"
  - ".bundle/**/*"
  - "misc/**/*"
  - "plugins/mitamae-plugin-resource-cron/**/*"
  - "spec/**/*"
  - "test/**/*"
  - "vendor/**/*"

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Metrics/ClassLength:
  Max: 400

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Max: 40

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/FrozenStringLiteralComment:
  Enabled: false

# MItamae extensions need to be specific with ::
Style/RedundantConstantBase:
  Enabled: false

# doesnt exist in mruby-3.0
Style/NumericPredicate:
  Enabled: false

# i like it
Style/ParallelAssignment:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: single_quotes

Style/FormatStringToken:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Itamae/RecipePath:
  Enabled: false
