---
plugins:
  - rubocop-rake
  - rubocop-itamae
  - rubocop-thread_safety
  - rubocop-performance
  

AllCops:
  NewCops: enable
  Include:
  - Rakefile
  - Gemfile
  - "*.gemspec"
  - "cookbooks/**/*"
  - "plugins/**/*"
  - "lib/**/*"
  - "bin/hocho"
  Exclude:
  - "bin/**/*"
  - "cookbooks/*/files/**/*"
  - "cookbooks/*/templates/**/*"
  - ".bundle/**/*"
  - "misc/**/*"
  - "plugins/mitamae-plugin-resource-cron/**/*"
  - "spec/**/*"
  - "test/**/*"
  - "vendor/**/*"

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
  Max: 30

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 35

Metrics/PerceivedComplexity:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: single_quotes

Style/FormatStringToken:
  Enabled: false
