---
creation_rules:
  - path_regex: "\\.yml$"
    encrypted_comment_regex: "@encrypt"
    pgp: 79F51922C72D82B81B2A20C234B4AFADB4E7D7A3

stores:
  json:
    indent: 2
  json_binary:
    indent: 2
  yaml:
    indent: 2
