# yamllint disable rule:line-length
b0rsch:
  properties:
    dns_shortname: b0
    run_list:
      - dickd
      - knot
      - mail
      - tor
    # @encrypt
    network_setup:
      v4:
        address: 172.105.89.59
        gateway: 172.105.89.1
        resolvers:
          - 139.162.130.5
          - 139.162.131.5
          - 139.162.132.5
          - 139.162.133.5
          - 139.162.134.5
      v6:
        address: 2a01:7e01::f03c:92ff:fe91:dc90
        gateway: fe80::1%vio0
        resolvers:
          - 2a01:7e01::5
          - 2a01:7e01::9
          - 2a01:7e01::7
          - 2a01:7e01::c
          - 2a01:7e01::2

f0rk:
  properties:
    dns_shortname: f0
    run_list:
      - dickd
      - knot
      - httpd
    # @encrypt
    network_setup:
      v4:
        address: 152.53.60.123
        gateway: 152.53.60.1
        resolvers:
          - 46.38.225.230
          - 46.38.252.230
      v6:
        address: 2a0a:4cc0:40:2074::1
        gateway: fe80::1%vio0
        resolvers:
          - 2a03:4000:0:1::e1e6
          - 2a03:4000:8000::fce6

airstrip1:
  properties:
    dns_shortname: a1
    run_list:
      - dickd
      - knot
      - mail
      - lego
    # @encrypt
    network_setup:
      v4:
        address: 139.162.204.177
        gateway: 139.162.204.1
        resolvers:
          - 176.58.116.5
          - 176.58.121.5
          - 151.236.220.5
          - 212.71.253.5
          - 109.74.192.20
      v6:
        address: 2a01:7e00::f03c:92ff:fe91:dc38
        gateway: fe80::1%vio0
        resolvers:
          - 2a01:7e00::9
          - 2a01:7e00::3
          - 2a01:7e00::c
          - 2a01:7e00::5
          - 2a01:7e00::6
